(function initMrState(global) {
  const {
    SPECIAL_ENTRY_ICONS,
    NAV_GROUP_ORDER,
    TIMELINE_EVENT_TAG_HINTS,
    TIMELINE_LOCATION_TAG_HINTS,
    TIMELINE_SOURCE,
    TIMELINE_ORG_TAG_HINTS,
    TIMELINE_THEME_TAG_HINTS,
    MR_UI_STATE_KEY,
    MAX_ROW_UPLOAD_BYTES,
    MAX_TIMELINE_PORTRAIT_QUEUE,
    ENABLE_DIRECT_PROBES,
    STORY_SET_PRESETS,
    STORY_VOICE_TAGS,
    CHARSHEET_TONE_OPTIONS,
    CHARSHEET_PRECISION_OPTIONS,
    CHARSHEET_CAPS_OPTIONS,
    CHARSHEET_HONESTY_OPTIONS,
    CHARSHEET_FORMALITY_OPTIONS,
    CHARSHEET_COLOR_PALETTE,
    CHARSHEET_FONT_VIBES,
    CHARSHEET_MODE_OPTIONS,
    ICON_SYMBOLS
  } = global.MR_CONSTANTS || {};

  global.MR_DATA = function createMrData() {
    const bootState = (() => {
      try {
        return JSON.parse(window.localStorage.getItem(MR_UI_STATE_KEY) || '{}') || {};
      } catch {
        return {
          isEditingActiveEntryRaw: false,
          activeEntryRawDraft: '',
          activeEntryRawSaving: false,
          activeEntryRawError: '',
        };
      }
    })();
    return {
      secureMediaToken: '',
      meta: {},
      storyMetadata: null,
      yearWriterId: '',
      versions: {},
      yearThemes: {},
      appLoading: true,
      isSwitchingYear: false,
      themeCustomizerOpen: false,
      themeCustomizerTargetYear: 'default',
      themeCustomizerData: {},
      themeCustomizerOriginalData: {},
      themeCustomizerColors: [
        '--bg',
        '--page',
        '--ink',
        '--ink2',
        '--dim',
        '--accent',
        '--border',
        '--sidebar-bg',
        '--sidebar-text',
        '--sidebar-active'
      ],
      themeCustomizerFonts: [
        '--font-body',
        '--font-serif',
        '--font-mono',
        '--font-display'
      ],
      characterCore: {},
      catalog: null,
      activeYear: String(bootState.year || ''),
      activeYearSourceFile: 'index.json',
      entries: [],
      activeEntryId: String(bootState.entryId || ''),
      iconPickerOpen: false,
      iconPickerTarget: '',
      iconPickerQuery: '',
      iconPickerSelection: '',
      iconPickerList: [
        'activity', 'airplay', 'alert-circle', 'alert-octagon', 'alert-triangle', 'align-center', 'align-justify', 'align-left', 'align-right', 'anchor', 'archive', 'arrow-down', 'arrow-down-circle', 'arrow-down-left', 'arrow-down-right', 'arrow-left', 'arrow-left-circle', 'arrow-right', 'arrow-right-circle', 'arrow-up', 'arrow-up-circle', 'arrow-up-left', 'arrow-up-right', 'at-sign', 'award', 'bar-chart', 'bar-chart-2', 'battery', 'bell', 'bluetooth', 'book', 'bookmark', 'box', 'briefcase', 'calendar', 'camera', 'cast', 'check', 'check-circle', 'check-square', 'chevrons-down', 'chevrons-left', 'chevrons-right', 'chevrons-up', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'clipboard', 'clock', 'cloud', 'code', 'codepen', 'coffee', 'columns', 'command', 'compass', 'copy', 'corner-down-left', 'corner-down-right', 'corner-up-left', 'corner-up-right', 'cpu', 'credit-card', 'crop', 'crosshair', 'database', 'delete', 'disc', 'download', 'download-cloud', 'droplet', 'edit-2', 'edit-3', 'external-link', 'eye', 'eye-off', 'feather', 'file', 'file-minus', 'file-plus', 'file-text', 'film', 'filter', 'flag', 'folder', 'folder-minus', 'folder-plus', 'frown', 'gift', 'git-branch', 'git-commit', 'git-merge', 'git-pull-request', 'globe', 'grid', 'hard-drive', 'hash', 'headphones', 'heart', 'home', 'image', 'inbox', 'info', 'instagram', 'key', 'layers', 'layout', 'life-buoy', 'link', 'list', 'loader', 'lock', 'log-in', 'log-out', 'mail', 'map', 'map-pin', 'maximize', 'maximize-2', 'meh', 'menu', 'message-circle', 'message-square', 'mic', 'minimize', 'minimize-2', 'minus', 'monitor', 'moon', 'more-horizontal', 'more-vertical', 'move', 'music', 'navigation', 'octagon', 'package', 'paperclip', 'pause', 'phone', 'pie-chart', 'play', 'play-circle', 'plus', 'plus-circle', 'pocket', 'power', 'printer', 'refresh-cw', 'refresh-ccw', 'repeat', 'rewind', 'rocket', 'rss', 'save', 'scissors', 'search', 'send', 'server', 'settings', 'share-2', 'shield', 'shield-off', 'shopping-bag', 'shopping-cart', 'shuffle', 'sidebar', 'skip-back', 'skip-forward', 'slash', 'sliders', 'smartphone', 'smile', 'speaker', 'square', 'star', 'stop-circle', 'sun', 'tablet', 'tag', 'target', 'terminal', 'thermometer', 'thumbs-down', 'thumbs-up', 'toggle-left', 'toggle-right', 'tool', 'trash', 'trending-down', 'trending-up', 'triangle', 'truck', 'twitter', 'umbrella', 'unlock', 'upload', 'upload-cloud', 'user', 'users', 'video', 'volume', 'watch', 'wifi', 'wind', 'x', 'x-circle', 'x-octagon', 'x-square', 'youtube', 'zap', 'zoom-in', 'zoom-out',
        'ph-dog', 'ph-cat', 'ph-bird', 'ph-fish', 'ph-rabbit', 'ph-horse', 'ph-paw-print', 'ph-knife', 'ph-sword', 'ph-shield', 'ph-skull', 'ph-ghost', 'ph-detective', 'ph-mask-happy', 'ph-mask-sad', 'ph-alien', 'ph-brain', 'ph-atom', 'ph-dna', 'ph-flask', 'ph-test-tube', 'ph-microscope', 'ph-telescope', 'ph-cactus', 'ph-tree', 'ph-flower-lotus', 'ph-campfire', 'ph-mountains', 'ph-waves', 'ph-bridge', 'ph-building', 'ph-factory', 'ph-tent', 'ph-binocular', 'ph-compass', 'ph-globe-hemisphere-west', 'ph-airplane-tilt', 'ph-train', 'ph-car', 'ph-bicycle', 'ph-bus', 'ph-truck', 'ph-boat', 'ph-anchor', 'ph-first-aid', 'ph-heartbeat', 'ph-stethoscope', 'ph-syringe', 'ph-pill', 'ph-lightning', 'ph-fire', 'ph-drop'
      ],
      sidebarExportOpen: false,
      search: '',
      mobileSidebarCollapsed: true,
      wideMediaBySrc: {},
      themeVarKeys: [],
      baseThemeVars: {},
      xrayEnabled: false,
      navGroupOrder: Array.isArray(bootState.navGroupOrder) ? bootState.navGroupOrder : [],
      navGroupOrderSaving: false,
      collapsedGroups: (bootState.collapsedGroups && typeof bootState.collapsedGroups === 'object') ? bootState.collapsedGroups : {},
      xrayInitScheduled: false,
      yearVariants: {},
      activeYearVariantKey: (() => {
        try {
          return JSON.parse(window.localStorage.getItem('mr_variants_v1') || '{}') || {};
        } catch {
          return {};
        }
      })(),
      pendingYear: '',
      rowDropState: {},
      rowImageFailedByKey: {},
      pendingRowPick: null,
      rowSubtitleDrafts: {},
      rowSubtitleSaving: {},
      timelineEvents: [],
      timelineLoading: false,
      timelineLimit: bootState.timelineLimit ? Number(bootState.timelineLimit) : 50,
      timelineError: '',
      timelineSearch: String(bootState.timelineSearch || ''),
      timelineSearchLocal: String(bootState.timelineSearch || ''),
      timelineYearFrom: bootState.timelineYearFrom ? Number(bootState.timelineYearFrom) : null,
      timelineYearTo: bootState.timelineYearTo ? Number(bootState.timelineYearTo) : null,
      timelineMonthFrom: bootState.timelineMonthFrom || '',
      timelineMonthTo: bootState.timelineMonthTo || '',
      timelineMonthsOpen: bootState.timelineMonthsOpen === true,
      timelineExcludeYearRange: bootState.timelineExcludeYearRange === true,
      timelineYearRanges: Array.isArray(bootState.timelineYearRanges)
        ? bootState.timelineYearRanges
        : (
          (bootState.timelineYearFrom || bootState.timelineYearTo)
            ? [{
                from: bootState.timelineYearFrom ? Number(bootState.timelineYearFrom) : null,
                to: bootState.timelineYearTo ? Number(bootState.timelineYearTo) : null,
                monthFrom: bootState.timelineMonthFrom || '',
                monthTo: bootState.timelineMonthTo || '',
                exclude: bootState.timelineExcludeYearRange === true,
                id: String(Date.now() + Math.random())
              }]
            : []
        ),
      timelineActiveTags: Array.isArray(bootState.timelineActiveTags)
        ? bootState.timelineActiveTags.map((tag) => String(tag || '').trim()).filter(Boolean)
        : [],
      timelineActiveWordTags: Array.isArray(bootState.timelineActiveWordTags)
        ? bootState.timelineActiveWordTags.map((w) => String(w || '').trim()).filter(Boolean)
        : [],
      heartbeatDragging: false,
      heartbeatDragSelection: { from: null, to: null },
      heartbeatMode: bootState.heartbeatMode || 'full',
       heartbeatZoom: Number.isFinite(Number(bootState.heartbeatZoom)) ? Number(bootState.heartbeatZoom) : 0,
       timelineTagMode: bootState.timelineTagMode || 'or', // 'or' (sum) vs 'and' (intersection)
       timelineFiltersCollapsed: bootState.timelineFiltersCollapsed === true,
       timelinePortraitsVisible: bootState.timelinePortraitsVisible !== false,
       timelineDateCreatedFilterMode: bootState.timelineDateCreatedFilterMode || 'all',
       timelineDateCreatedCustom: bootState.timelineDateCreatedCustom || '',
       timelineReverseOrder: bootState.timelineReverseOrder === true,
       timelineSequentialMode: (bootState.timelineSequentialMode === true || bootState.timelineRecursiveMode === true),
       showLifecycleMilestones: bootState.showLifecycleMilestones === true,
       timelineCharactersOnly: bootState.timelineCharactersOnly === true,
       timelineDialogueBubbles: bootState.timelineDialogueBubbles !== false,
      massTagInput: '',
      hoverCardPos: { x: 0, y: 0 },
 
      // Confirmation Modal
      confirmModalOpen: false,
      confirmModalTitle: '',
      confirmModalBody: '',
      confirmModalConfirmLabel: 'Confirm',
      confirmModalCancelLabel: 'Cancel',
      confirmModalAction: null,
 
      // Manual Copy Fallback Modal
      manualCopyOpen: false,
      manualCopyFormat: '',
      manualCopyCharId: '',
      manualCopyText: '',

      // Charsheet Prompt System
      charsheetPromptOpen: false,
      charsheetPromptWriter: bootState.charsheetPromptWriter || '',
      charsheetPromptTone: bootState.charsheetPromptTone || 'sincere',
      charsheetPromptPrecision: bootState.charsheetPromptPrecision || 'precise',
      charsheetPromptCaps: bootState.charsheetPromptCaps || 'all lowercase',
      charsheetPromptHonesty: bootState.charsheetPromptHonesty || 'honest',
      
      // Character Core Modal
      coreEditMode: bootState.coreEditMode === true,
      characterCoreModalOpen: false,
      characterCoreFormData: {
        characterId: '',
        mode: 'character', // 'character' | 'entity' | 'redirect'
        entityCategory: 'organizations',
        redirectTarget: '',
        'full name': '',
        birthDate: '',
        ageAtEntry: '',
        contextYear: null,
        gender: '',
        ethnicity: '',
        navGroup: '',
        iconKey: ''
      },
      characterCoreSaving: false,
      characterCoreSaveError: '',
      deleteConfirmationOpen: false,
      
      // Relationship Editor Modal
      relationshipModalOpen: false,
      relationshipModalIsEdit: false,
      relationshipModalFormData: {
        id: '',
        newId: '',
        label: '',
        type: 'romance',
        startDate: '',
        splitDate: '',
        membersRaw: '',
        childrenRaw: '',
        notes: '',
        historyText: ''
      },
      relationshipModalSaving: false,
      relationshipModalError: '',
      demographicsBulkEditOpen: false,
      demographicsSelectedCharacters: [],
      demographicsBulkFormData: {
        updateGender: false,
        updateEthnicity: false,
        updateNationality: false,
        updateNavGroup: false,
        updateGroups: false,
        gender: '',
        ethnicity: '',
        nationality: '',
        navGroup: '',
        groups: [],
        newGroupInput: ''
      },
      demographicsBulkSaving: false,
      demographicsBulkSaveError: '',
      demographicsMissingFilter: 'all',
      demographicsChartFilter: null,
      demographicsSelectedGenders: [],
      demographicsSelectedEthnicities: [],
      demographicsSelectedNationalities: [],
      demographicsSelectedPortraits: [],
      demographicsSelectedGroups: [],
      demographicsFilterIncompleteOnly: true,
      demographicsSearchQuery: '',
      demographicsSidebarOpen: false,
      demographicsGeneratorCount: 5,
      demographicsGeneratorEquitable: true,
      demographicsSuggestions: [],
      demographicsSuggestionsLoading: false,
      demographicsSuggestionsError: '',
      activeDateTab: 'birth',
      selectedMiscPortraitFile: null,
      miscPortraitPreviewUrl: '',
      miscPortraitUploading: false,
      miscPortraitUploadSuccess: false,
      miscPortraitUploadError: '',
      charsheetPromptFormality: bootState.charsheetPromptFormality || 'casual',
      charsheetPromptSubjects: {}, // { charId: true/false }
      charsheetPromptNotice: '',
      charsheetPromptLoading: false,
      charsheetStyleColors: bootState.charsheetStyleColors || [],
      charsheetStyleFontVibe: bootState.charsheetStyleFontVibe || 'gothic serif',
      charsheetStyleMode: bootState.charsheetStyleMode || 'dark',
      charsheetGeneratedPrompt: '',

      // Expose constants
      CHARSHEET_TONE_OPTIONS,
      CHARSHEET_PRECISION_OPTIONS,
      CHARSHEET_CAPS_OPTIONS,
      CHARSHEET_HONESTY_OPTIONS,
      CHARSHEET_FORMALITY_OPTIONS,
      CHARSHEET_COLOR_PALETTE,
      CHARSHEET_FONT_VIBES,
      CHARSHEET_MODE_OPTIONS,

      _yearTimelineObserver: null,
      _yearTimelineIgnoreScroll: false,
      _yearTimelineScrollTimer: null,
      timelineDateEditingKey: '',
      timelineDateDraftByKey: {},
      timelineDateSavingByKey: {},
      timelineDateErrorByKey: {},
      timelineTextEditingKey: '',
      timelineTextDraftByKey: {},
      timelineTextSavingByKey: {},
      timelineTextErrorByKey: {},
      timelineExpandedKeys: {},
      timelineOverflows: {},
      timelineSelectedKeys: {},
      timelineSelectAllIncludesCutoff: false,
      timelineBatchAnchorKey: '',
      timelineBatchShiftYears: 0,
      timelineBatchShiftMonths: 0,
      timelineBatchShiftDays: 0,
      timelineBatchSaving: false,
      timelineBatchNotice: '',
      timelineBatchNoticeTone: '',
      timelinePortraitByEvent: {},
      timelineTagDropdownKey: '',
      portraitManifest: {},
      portraitPrefix: 'portraits',
      journeyPortraitByYearChar: {},
      journeyPortraitFailedByYearChar: {},
      relationshipTree: [],
      relationshipTreeLoading: false,
      relationshipTreeError: '',
      relationshipPortraitByYearChar: {},
      relationshipPortraitFailedByYearChar: {},
      relationshipTreeZoomStates: {}, // { groupIndex: { x, y, scale, isDragging } }
      relationshipTreeSimulatedGroups: [], // The real-time graph data
      relationshipFilter: 'all', // all, historical, operational, personal
      selectedTreeCharacter: null, // characterId when clicked in tree
      entitiesRegistry: {},
      relationships: [],
      relationshipsLoading: false,
      relationshipsError: '',
      relationshipDateEditingKey: '',
      relationshipDateDraftByKey: {},
      relationshipDateSavingByKey: {},
      relationshipDateErrorByKey: {},
      relationshipPortraitByYearChar: {},
      relationshipPortraitFailedByYearChar: {},
      mediaYears: [],
      timelineList: ['earthborn'],
      activeTimeline: 'earthborn',
      timelineCreatorOpen: false,
      newTimelineName: '',
      notebooks: [],
      notebooksLoading: false,
      notebooksError: '',
      activeNotebookId: String(bootState.notebookId || ''),
      notebookSearch: String(bootState.notebookSearch || ''),
      notebookRulesEnabled: bootState.notebookRulesEnabled !== false,
      notebookSearchActiveEntryKey: '',
      notebookParagraphTargetKey: '',
      notebookTimelineLinks: [],
      notebookImportModalOpen: false,
      notebookImportId: '',
      notebookImportNumber: '',
      notebookImportTitle: '',
      notebookImportSubtitle: '',
      notebookImportMetadata: '',
      notebookImportDate: '',
      notebookImportFilename: '',
      notebookImportEntryId: '',
      notebookImportEntryTitle: 'Start',
      notebookImportEntryDate: '',
      notebookImportStoryText: '',
      notebookImportSaving: false,
      notebookImportError: '',
      addRecordModalOpen: false,
      addRecordType: 'timeline',
      addRecordDate: '',
      addRecordTitle: '',
      addRecordDescription: '',
      addRecordTags: [],
      addRecordRelationshipId: '',
      addRecordRelationshipLabel: '',
      addRecordRelationshipType: 'relationship',
      addRecordRelationshipStartDate: '',
      addRecordRelationshipSplitDate: '',
      addRecordRelationshipMembers: '',
      addRecordRelationshipChildren: '',
      addRecordRelationshipNotes: '',
      addRecordRelationshipHistoryDate: '',
      addRecordRelationshipHistoryEvents: '',
      addRecordBulkText: '',
      addRecordParsedCount: 0,
      addRecordParsedTags: [],
      addRecordSaving: false,
      addRecordFormatting: false,
      addRecordError: '',
      addRecordSuccess: '',
      datePickerReady: false,
      datePickerInitializedCount: 0,
      dateMenuOpen: false,
      dateMenuX: 0,
      dateMenuY: 0,
      dateMenuYear: '',
      dateMenuMonth: '01',
      dateMenuDay: '01',
      dateMenuContext: null,
      dateMenuApplying: false,
      dateMenuError: '',
      storyExportOpen: false,
      storyExportLimitToSelected: false,
      storyExportSelections: {},
      storyExportProtagonistId: '',
      storyExportRelationshipOpen: false,
      storyExportRelationshipSelections: {},
      storyExportPerspective: 'first person',
      storyExportSet: 'drama',
      storyExportDialogStyle: 'character_colon_quote',
      storyExportIncludeInternalDialogue: true,
      storyExportIncludeStoryFormat: true,
      storyExportStyleTagSelections: {
        observational: true,
        precise: true,
        honest: true
      },
      storyExportExtraInstructions: '',
      timelineSequentialExcludedTags: [],
      timelineAddEventOpen: bootState.timelineAddEventOpen === true,
      timelineAddEventInput: '',
      timelineAddEventDateCreated: (() => {
        const d = new Date();
        const offset = d.getTimezoneOffset();
        const localDate = new Date(d.getTime() - (offset * 60 * 1000));
        return localDate.toISOString().split('T')[0];
      })(),
      timelineAddEventSaving: false,
      timelineAddEventError: '',
      timelineAddEventSuccess: '',
      storyExportDynamicOptions: {
        includeEscalation: true,
        includeTwists: true,
        includeDialogueMomentum: true,
        includeVividSetting: true,
        includeMoralDilemmas: true,
        includeCliffhangers: false
      },
      storyExportPreferRelationshipCast: false,
      storyExportIncludeRelationships: true,
      storyExportError: '',
      storyExportPortraitByYearChar: {},
      storyExportPortraitFailedByYearChar: {},
      storyExportTimelineLimitMode: 'all',
      storyExportTimelineSelections: {},
      storyExportTimelineOpen: false,
      pageReaderUiVisible: bootState.pageReaderUiVisible === true,
      pageReaderReading: false,
      pageReaderProgress: '0 / 0',
      pageReaderCurrentIndex: 0,
      pageReaderTotalSegments: 0,
      pageReaderReady: false,
      sfxManifest: [],

      // Image Prompt Maker
      imgPromptOpen: false,
      imgPromptEvent: null,
      imgPromptEventIndex: 0,
      imgPromptCharacters: [],
      imgPromptNaming: bootState.imgPromptNaming || 'names',
      imgPromptOrientation: bootState.imgPromptOrientation || 'vertical',
      imgPromptType: bootState.imgPromptType || 'candid',
      imgPromptFraming: bootState.imgPromptFraming || 'head-to-waist',
      imgPromptBackground: bootState.imgPromptBackground || 'auto',
      imgPromptClothing: bootState.imgPromptClothing || 'auto',
      imgPromptCustomBackground: bootState.imgPromptCustomBackground || '',
      imgPromptActiveActions: bootState.imgPromptActiveActions || {},
      imgPromptCustomAction: bootState.imgPromptCustomAction || '',
      imgPromptMood: bootState.imgPromptMood || 'relaxed',
      imgPromptLighting: bootState.imgPromptLighting || 'natural',
      imgPromptStyle: bootState.imgPromptStyle || 'candid-phone',
      imgPromptIncludeAppearance: bootState.imgPromptIncludeAppearance !== false,
      imgPromptIncludeContext: bootState.imgPromptIncludeContext !== false,
      imgPromptContextMode: bootState.imgPromptContextMode || (bootState.imgPromptIncludeContext === false ? 'none' : 'brief'),
      imgPromptReferenceYear: bootState.imgPromptReferenceYear || '',
      imgPromptAddCharacterInput: '',
      imgPromptLookingAt: bootState.imgPromptLookingAt || 'none',
      imgPromptCustomLookingAt: bootState.imgPromptCustomLookingAt || '',
      imgPromptExtraInstructions: bootState.imgPromptExtraInstructions || '',
      imgPromptMoodIntensity: bootState.imgPromptMoodIntensity || 5,
      imgPromptLightingIntensity: bootState.imgPromptLightingIntensity || 5,
      imgPromptExcludedCharacters: [],
      imgPromptAdaptAge: false,
      imgPromptMotionBlur: bootState.imgPromptMotionBlur === true,
      imgPromptAspectRatio: bootState.imgPromptAspectRatio || '9:16',
      imgPromptCharacterPositions: bootState.imgPromptCharacterPositions || {},
      imgPromptGeneratedText: '',
      imgPromptNewspaperHeadline: '',
      imgPromptPresets: null,
      imgPromptPresetsLoading: false,
      imgPromptSavedPresets: (() => {
        try {
          return JSON.parse(window.localStorage.getItem('mr.img_prompt_saved_presets') || '{}') || {};
        } catch {
          return {};
        }
      })(),
      imgPromptNewPresetName: '',

      // Statistics
      characterStats: [],
      showCharacterStatsModal: false,

      // SillyTavern Character Card Generator
      sillyTavernOpen: false,
      sillyTavernEvent: null,
      sillyTavernEventIndex: 0,
      sillyTavernCharacters: [],
      sillyTavernSelectedChar: '',
      sillyTavernSelectedCharB64: '',
      sillyTavernGeneratedPrompt: '',
      sillyTavernTab: 'prompt',
      sillyTavernPastedJson: '',
      sillyTavernFinalizedJson: '',
      sillyTavernError: ''
    };
  };
}(window));
